### ISSUE TITLE
UTF-8 CSV file with BOM adds extra space character to first parsed field name

### ISSUE THREAD

**Issue by cormip** [sindresorhus/neat-csv#10]
e.g. UTF-8 file with BOM:

```
id,varA,varB
1,0,0
2,0,0
3,0,0
```

imports as:

```
[
  {
    ' id': '1',
    varA: '0',
    varB: '0'
  },
  {
    ' id': '2',
    varA: '0',
    varB: '0'
  },
  {
    ' id': '3',
    varA: '0',
    varB: '0'
  }
]
```

I was able to work around this by converting the file to ANSI.

**Comment by sindresorhus** [comment]
This should be reported to the underlaying parser: https://github.com/mafintosh/csv-parser

**Comment by sindresorhus** [comment]
By the way, UTF-8 should not have a BOM.

**Comment by cormip** [comment]
The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use. I only ran into this because the export file created by Toad for MySQL was UTF-8 encoded with a BOM.

**Comment by dmikester1** [comment]
I'm running into this same issue!  My column name should be "Chemical", but it's not matching "Chemical" because there is a character in front of it similar to a space but it's like a hidden space.  Is there a work-around for this?

I'm not sure what BOM means, but it's just a CSV I saved out from Excel.

Look at the key field in this object:
![image](https://user-images.githubusercontent.com/8491610/89314359-2b8a7780-d63f-11ea-9e9f-db834ac5a153.png)

**Comment by cormip** [comment]
[BOM](https://en.wikipedia.org/wiki/Byte_order_mark)

Perform a Replace() function on the column name to remove all characters that don't belong. e.g. anything except a-zA-Z0-9 (or whatever else you need)
